-- Database Export for IC Scanner
-- Table: inspection_records

CREATE TABLE public.inspection_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    vendor text,         -- Nullable
    lot_id text,         -- Nullable
    part_number text,    -- Nullable
    result text NOT NULL,
    confidence numeric NOT NULL,
    operator text,       -- Nullable
    image_url text       -- Nullable
);

